const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const modules=process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES;
global.JSZip=require(modules+'/jszip');
global.DOMParser=require(modules+'/@xmldom/xmldom').DOMParser;require('../src/xml-reader.js');
const C=require('../src/core.js');
const asFile=(name,bytes)=>({name,size:bytes.length,arrayBuffer:async()=>Uint8Array.from(bytes).buffer});
let checks=0;function check(f){f();checks++;}
(async()=>{
 const dir=process.env.COURSE_TEST_INPUT;
 if(dir){
  const files=fs.readdirSync(dir).filter(x=>x.endsWith('.xlsx')).sort();
  const exports=[];
  for(const n of files)exports.push(await C.parseXlsx(fs.readFileSync(path.join(dir,n)),n,'test-hash'));
  check(()=>assert.deepEqual(exports.map(x=>x.item_count),[22,46,23]));
  check(()=>assert.equal(exports.reduce((n,c)=>n+c.modules.length,0),9));
  check(()=>assert.equal(exports.reduce((n,c)=>n+c.modules.reduce((a,m)=>a+m.lessons.length,0),0),30));
  check(()=>assert.equal(new Set(exports.map(c=>c.branch_id)).size,3));
  check(()=>assert.equal(exports.reduce((n,c)=>n+c.item_count,0),91));
  check(()=>assert(exports.every(c=>c.modules.every(m=>m.id&&m.title&&m.lessons.every(l=>l.id&&l.items.every(i=>i.id&&!i.body_available))))));
  console.log('Supplied Coursera XLSXs: 3 courses, 9 modules, 30 lessons, 91 items verified.');
 }
 const z=new JSZip();
 z.file('imsmanifest.xml',`<manifest identifier="m"><metadata><title>Test Science</title></metadata><organizations><organization identifier="org"><title>Course</title><item identifier="m1"><title>Module One</title><item identifier="a" identifierref="ra"><title>Waves</title></item><item identifier="b" identifierref="rb"><title>Waves</title></item><item identifier="c" identifierref="rc"><title>Faults</title></item></item></organization></organizations><resources><resource identifier="ra" type="webcontent" href="pages/a.html"><file href="pages/a.html"/></resource><resource identifier="rb" href="pages/b.html"><file href="pages/b.html"/></resource><resource identifier="rc" href="quiz.xml"><file href="quiz.xml"/><dependency identifierref="rd"/></resource><resource identifier="rd"><file href="captions.vtt"/></resource><resource identifier="missing" href="missing.html"/><resource identifier="external" href="https://example.org/lesson"/></resources></manifest>`);
 z.file('pages/a.html','<h1>Waves</h1><p>P waves &amp; S waves.</p><script>SECRET_BAD_SCRIPT()</script><a href="https://example.org/video">Video</a>');
 z.file('pages/b.html','<h1>Waves</h1><p>A distinct lesson with the same title.</p>');
 z.file('quiz.xml','<questestinterop><item ident="q1"><presentation><material><mattext><![CDATA[<p>Which fault?</p>]]></mattext></material></presentation><response_label ident="A">Reverse fault</response_label><respcondition><conditionvar><varequal respident="response1">A</varequal></conditionvar><setvar varname="SCORE">100</setvar></respcondition></item></questestinterop>');
 z.file('captions.vtt','WEBVTT\n\n00:00:01.000 --> 00:00:03.000\nMeasured shaking differs.');
 z.file('video.mp4',new Uint8Array([0,1,2]));z.file('figure.png',new Uint8Array([0,1,2]));
 const nested=new JSZip();nested.file('nested-reading.txt','Nested source evidence.');z.file('assessment.zip',await nested.generateAsync({type:'uint8array'}));
 const bytes=await z.generateAsync({type:'uint8array'});const f=asFile('course.imscc',bytes);const s=await C.processFiles([f],{title:'Sample'});const source=s.sources[0];
 check(()=>assert.equal(source.manifests[0].items.length,4));
 check(()=>assert.equal(source.documents.length,5));
 check(()=>assert.equal(source.unread.filter(x=>x.kind==='media').length,1));
 check(()=>assert.equal(source.unread.filter(x=>x.kind==='image').length,1));
 check(()=>assert(source.unread.some(x=>x.path==='missing.html'&&x.kind==='missing_reference')));
 check(()=>assert(source.external_links.some(x=>x.url==='https://example.org/lesson')));
 check(()=>assert(source.documents.some(x=>x.path==='assessment.zip!/nested-reading.txt')));
 check(()=>assert(!source.documents.some(x=>x.text.includes('SECRET_BAD_SCRIPT'))));
 check(()=>assert(source.documents.some(x=>x.text.includes('P waves & S waves'))));
 check(()=>assert(source.documents.find(x=>x.path==='quiz.xml').text.includes('respident=response1')));
 check(()=>assert(source.documents.find(x=>x.path==='captions.vtt').associations.some(a=>a.items.some(i=>i.id==='c'))));
 const course={filename:'x.xlsx',title:'Target',item_count:2,modules:[{title:'Target Module',lessons:[{title:'L',items:[{id:'one',title:'Waves'},{id:'two',title:'Faults'}]}]}]};
 const matches=C.matchItems([course],[source]);
 check(()=>assert.equal(matches[0].status,'ambiguous_title'));
 check(()=>assert.equal(matches[1].status,'unique_title_candidate'));
 check(()=>assert(matches.every(m=>m.verified===false)));
 const files=C.bundleFiles(s);check(()=>assert(files['COURSE_CONTEXT_01.txt'].includes('Nested source evidence.')));
 const bz=new JSZip();for(const [n,t]of Object.entries(files))bz.file(n,t);const bundle=await bz.generateAsync({type:'uint8array'});
 const restored=await C.processFiles([asFile('saved.zip',bundle),asFile('feedback.txt',Buffer.from('Partner approved proposal A.'))],{phase:'final'});
 check(()=>assert.equal(restored.sources.length,1));check(()=>assert.equal(restored.sources[0].sha256,source.sha256));check(()=>assert.equal(restored.references.length,1));check(()=>assert.equal(restored.phase,'final'));
 const empty=C.newSession('Old');empty.issues=[{file:'Source evidence',reason:'No readable source package was supplied.'}];
 const resolved=await C.processFiles([asFile('SESSION.json',Buffer.from(JSON.stringify(empty))),f]);
 check(()=>assert(!resolved.issues.some(x=>x.file==='Source evidence')));
 const bad=new JSZip();bad.file('../evil.txt','no');await assert.rejects(C.parseCartridge(await bad.generateAsync({type:'uint8array'}),'bad.zip',null),/unsafe path/);checks++;
 check(()=>assert.throws(()=>C.XML('<!DOCTYPE x><x/>'),/not supported/));
 const split=C.splitContext(['ONE\n'+'α'.repeat(150),'TWO\n'+'β'.repeat(150),'THREE'],100);
 check(()=>assert.equal(split.join('').match(/α/g).length,150));check(()=>assert.equal(split.join('').match(/β/g).length,150));check(()=>assert(split.join('').includes('THREE')));
 const ab=new AbortController();ab.abort();await assert.rejects(C.processFiles([f],{signal:ab.signal}),{name:'AbortError'});checks++;
 console.log(`${checks} extraction, provenance, ambiguity, resume, coverage, splitting and cancellation checks passed.`);
})().catch(e=>{console.error(e);process.exitCode=1;});
